package codexs

import (
	"bytes"
	"strconv"
	"text/template"
)

const codexConfigTemplate = `# Generated by codexs. Edit the profile with ` + "`codexs update`" + `.
cli_auth_credentials_store = "file"
model_provider = "profile"

[model_providers.profile]
name = "profile"
wire_api = "responses"
base_url = {{.BaseURL}}
requires_openai_auth = true
`

func renderCodexConfig(baseURL string) string {
	tmpl := template.Must(template.New("config").Parse(codexConfigTemplate))
	var buf bytes.Buffer
	_ = tmpl.Execute(&buf, map[string]string{
		"BaseURL": tomlString(baseURL),
	})
	return buf.String()
}

func tomlString(value string) string {
	return strconv.Quote(value)
}
