package codexs

import (
	"strconv"
	"strings"
)

func renderCodexConfig(baseURL string) string {
	var b strings.Builder
	b.WriteString("# Generated by codexs. Edit the profile with `codexs update`.\n")
	b.WriteString("cli_auth_credentials_store = \"file\"\n")
	b.WriteString("model_provider = \"profile\"\n")
	b.WriteString("\n")
	b.WriteString("[model_providers.profile]\n")
	b.WriteString("name = \"profile\"\n")
	b.WriteString("wire_api = \"responses\"\n")
	b.WriteString("base_url = ")
	b.WriteString(tomlString(baseURL))
	b.WriteString("\n")
	b.WriteString("requires_openai_auth = true\n")
	return b.String()
}

func tomlString(value string) string {
	return strconv.Quote(value)
}
